### ISSUE TITLE
No sources 

### ISSUE THREAD

**Issue by Randomdude707** [DxCx/plugin.video.9anime#295]
I don't know if it's just me but I can't get any sources

**Comment by ghettowboy** [comment]
Noticed that they went from www6. To www7. In the url.... not sure if that's what it is.

**Comment by RedNinjaX** [comment]
I'm on it. Things should be fixed quickly

**Comment by xSLOWWx** [comment]
What is the estimated time? Sorry impatient 😂

**Comment by RedNinjaX** [comment]
Anywhere from a few minutes to maybe an hour but nothing more. I already see the problem and it's an easy fix 👌

**Comment by ruegnueg** [comment]
great 😉

**Comment by MobileSuitSadBoi** [comment]
@RedNinjaX you're the man thank you! Let us know if we need to update the add-on manually or we don't have to do anything

**Comment by RedNinjaX** [comment]
Should be working now 👌

**Comment by Randomdude707** [comment]
It's working thank you

**Comment by MobileSuitSadBoi** [comment]
It's working thank you! 🤜🤛

**Comment by ruegnueg** [comment]
great Team here 👍

**Comment by xSLOWWx** [comment]
Love this add on!

**Comment by MobileSuitSadBoi** [comment]
No sources again just now😑😑😑

**Comment by clutchylfg** [comment]
Not sure if this is the same issue but I can't even get the list of shows to pop up. I just get an error, tried to look at the logs but didn't find anything. I did just do a fresh install of the repo and 9anime, so I am on version .43

**Comment by JulGer** [comment]
Perhaps it's just about time to throw the towel...😞

**Comment by RedNinjaX** [comment]
The API is still working just fine and the Kodi plugin is still working on my end and 9anime hasn't changed anything so far so try the usual troubleshooting.

**Comment by MobileSuitSadBoi** [comment]
@RedNinjaX restarted Kodi and it's working again🤷🏽‍♂️🤷🏽‍♂️ sorry to bother you m8

**Comment by romxuk** [comment]
Working perfectly fine for me, if you make changes remember to reboot Kodi. sometimes it is needed to make changes take effect

**Comment by clutchylfg** [comment]
I took a look at my logs again, it says that the GetDirectory/CGUIMediaWindow is failing on all the requests, Any ideas?

ERROR: GetDirectory - Error getting plugin://plugin.video.9anime/popular_subbed
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.9anime/popular_subbed) failed

**Comment by roworit** [comment]
It's working now, also I was wondering if it was possible to make an option to hide dubbed Anime.

**Comment by clutchylfg** [comment]
Still not working for me :(

**Comment by ghettowboy** [comment]
@roworit what do you mean by hide dubs? If I'm not mistaken there are options for that labeled as "recent/popular subbed" and "recent/popular dubbed".

**Comment by roworit** [comment]
That's true but when I search by category I see almost all dubbed Anime.

**Comment by ghettowboy** [comment]
@RedNinjaX yeah.... it's not working for me either, not sure what's up.

**Comment by xSLOWWx** [comment]
Me as well. Tried to reset also and getting a could not find sources.

**Comment by RedNinjaX** [comment]
Yeah 9anime hasn't changed anything again. Our server is just having some weird issues right now, has nothing to do with them. Working on it

**Comment by RedNinjaX** [comment]
Alright should be working now

**Comment by clutchylfg** [comment]
I am still having the same get directory issue, any ideas on how to fix that?

**Comment by d1arkstar** [comment]
@RedNinjaX  I got issue it wont pull from the rapid video

**Comment by d1arkstar** [comment]
@RedNinjaX  say list out of range

**Comment by xSLOWWx** [comment]
So is rapidvideo server down?
Because to be honest thats the only one I use.

**Comment by xSLOWWx** [comment]
Yeah I get a error message saying check log info.
Any reason why it's doing that?

**Comment by HackedGameMaker** [comment]
Usually when a new update comes out for 9anime I always have to uninstall kodi and then reinstall it to fix the error message issue for me

**Comment by Randomdude707** [comment]
So all I have to do is uninstall kodi and reinstall it and then it should work again right ?

**Comment by FireWolf74** [comment]
you should not have to do that unless you remove the repo from your file manager.
![screenshot from 2018-07-02 18-06-14](https://user-images.githubusercontent.com/33334258/42188533-405ffb3e-7e22-11e8-827a-6d2a21b0adbf.png)

**Comment by Randomdude707** [comment]
Well im talking about the rapid video sources everthing else works just fine

**Comment by RedNinjaX** [comment]
@Randomdude707 a new update was released just a few minutes ago that fixes the RapidVideo issue

**Comment by clutchylfg** [comment]
I had to reinstall Kodi for it to work but it seems to be working fine now! Thanks!
