### ISSUE TITLE
can't find eliable sources 

### ISSUE THREAD

**Issue by Dranzera** [DxCx/plugin.video.9anime#36]
Hey there it says can't find eliable sources again is the site down?

**Comment by Dranzera** [comment]
Works again! Thanks 😊.

**Comment by rbz205** [comment]
I am having the source issue stated above. I notice some animes work while other have the issue. 

Thanks in advance!

**Comment by DxCx** [comment]
@rbz205 what happens if you retry right after?

**Comment by rbz205** [comment]
The ones I got to work were retries or worked first time lol. There are some animes where multiple retries still gave me either an error log message or cant find eliable sources.

**Comment by DxCx** [comment]
cool @rbz205 thanks for the report,
can you please give me an example of such anime so i can debug it?

**Comment by JinKudo** [comment]
Koe no katachi

**Comment by DxCx** [comment]
Thanks @JinKudo i'll try to debug it and report back
i was able at initial test to see it's indeed acts wired.

**Comment by rbz205** [comment]
@DxCx I have not tried it this morning, but yesterday night Eromanga sensei worked about 50 % of the time. 

Rokudenashi Majutsu Koushi to Akashic Records, Koe no katachi, Gabriel DropOut, and Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Gaiden: Sword Oratoria (subs) were having issues.

**Comment by p1wookie** [comment]
I've been having this issue for a couple weeks. Main ones I watch are Shingeki no Kyojin season 2 and Dragon Ball Super (dub)

**Comment by p1wookie** [comment]
Disregard previous comment. I saw you updated. Uninstalled old then downloaded and installed new one. Working again.

**Comment by Dranzera** [comment]
Also SD Gundam Gaiden says error log too.

**Comment by DxCx** [comment]
Guys i think i got enough examples, thank you all =)
my problem now is time 👍 
i'll try to find some time during the week to look at those and update you

**Comment by rbz205** [comment]
PS: I noticed you updated on another issue post and installed the new version. Now the addon seems to be working without​ issues on my part. 

Maybe a website issue or the new version works better? 

Thanks for all the work btw. I love the ability to watch shows in Kodi.

**Comment by DxCx** [comment]
@rbz205 Are the animes mentioned above are working now?
When i tried 'Koe no katachi' with latest it still havnt worked

**Comment by rbz205** [comment]
Yes, it seems to be working for me (including Koe no Katachi). I am using Kodi 17.1 on Nvidia Shield Tv. 

I just deleted my old addon and installed the new zip.

**Comment by DxCx** [comment]
Cool thanks for the report, will retry myself and close the issue if its
indeed working :)

**Comment by githubus11** [comment]
found two other possible issues:

first: if we request the sources of a video too fast, we will get a 503. (thats one of the reasons why you get sometimes a full list of possible servers and the other time you just get one)

second:
if a F1 or F2 is not available the program raises an exception and possibly get no source at all

i made a pushrequest to workaround those errors

**Comment by DxCx** [comment]
alright guys so thanks to @githubus11 who debugged this, it should be working now,
you are welcome to try it and report back (don't forget to reinstall the .zip)

**Comment by pinay26** [comment]
Still not working on some episode .. example--  b gata h kei (dub) episode 1

**Comment by hoppler** [comment]
Hi, reason is simple. file not online. if you goto 9anime directly youll se you get server error for f1 and f2. so no error on the plugin side

**Comment by pinay26** [comment]
and also b gata h kei (sub) episode 1 give spurce server F2 but none of the links work ar just maybe f2 server has problems

**Comment by pinay26** [comment]
@hoppler i see.. does the addon only gets the f1 and f2 links? coz the openload links seems to be working when i use a browser

**Comment by hoppler** [comment]
openload is disabled currently as we dont have a parser for them. so the addon only gets f1 and f2

**Comment by Dranzera** [comment]
Yugioh season 0 and Dragon Ball Super not working either since thisthis morning.

**Comment by githubus11** [comment]
9anime seems to be overloaded. but i found another issue as the f1 returns a grabber url with a paramter inluded. `grabInfo['grabber'] sometimes ends with /?server=23 so we have to concat with & instead of ?`

ill wait for 9anime to overcome the overload issue and will test it afterwards. but above is the reason why you sometimes dont get sources from f1

**Comment by roafhtun** [comment]
Could be cuz server is overload, I'm having the same problem today it's been like 3 hrs

**Comment by DxCx** [comment]
@githubus11 just contributed one more fix :)
let me know where you still see issues.. ;)

**Comment by jtipt** [comment]
@DxCx Nope, now it just shows "load xx server" then nothing happens, the sources do not appear.

**Comment by hoppler** [comment]
always check 9anime itelf if its working as for me 9anime still has server issues like no F2 and partial working F1. also please provide more information like the title and the episode so we others can look further into it.

**Comment by DxCx** [comment]
thanks @hoppler 👍

**Comment by githubus11** [comment]
After lookin into urlresolver we have the possibility to use openload too. it requires that the plugin https://github.com/tknorris/script.module.urlresolver is installed. if you have xstream it will get installed automatically. as i dont know right know how to install it with the plugin i cant provide a usefull patch for it. **if you have urlresolver installed** you can do the following to use openload:

in `.kodi/addons/plugin.video.9anime/addon.xml` change 
````xml
<requires>
    <import addon="xbmc.gui" version="5.12.0"/>
    <import addon="script.module.requests" version="2.12.4"/>
    <import addon="script.common.plugin.cache" version="2.5.5"/>
</requires>
````
to 
````xml
<requires>
    <import addon="xbmc.gui" version="5.12.0"/>
    <import addon="script.module.requests" version="2.12.4"/>
    <import addon="script.common.plugin.cache" version="2.5.5"/>
    <import addon="script.module.urlresolver" version="3.0.31"/>
</requires>
````

and in `.kodi/addons/plugin.video.9anime/resources/lib/ui/embed_extractor.py` change
````python
def __extract_9anime(url, page_content):
    episode_id = url.rsplit('/', 1)[1]
    url_info = urlparse.urlparse(url)
    domain = url_info.netloc
    scheme = url_info.scheme

    url_base = "%s://%s" % (scheme, domain)
    url = "%s/ajax/episode/info?id=%s&update=0" % (url_base, episode_id)
    set_request = NineAnimeTokenDecoder.set_request("%s/token?v1" % url_base, http.send_request)

    time.sleep(1)
    urlRequest = http.send_request(url, set_request=set_request)

    grabInfo = json.loads(urlRequest.text)
    if 'error' in grabInfo.keys():
        raise Exception('error while trying to fetch info: %s' %
                        grabInfo['error'])
    if grabInfo['type'] == 'iframe':
        return load_video_from_url(grabInfo['target'])
    elif grabInfo['type'] == 'direct':
        return __9anime_extract_direct(url, grabInfo)

    raise Exception('Unknown case, please report')
````
to
````python
def __extract_9anime(url, page_content):
    episode_id = url.rsplit('/', 1)[1]
    url_info = urlparse.urlparse(url)
    domain = url_info.netloc
    scheme = url_info.scheme

    url_base = "%s://%s" % (scheme, domain)
    url = "%s/ajax/episode/info?id=%s&update=0" % (url_base, episode_id)
    set_request = NineAnimeTokenDecoder.set_request("%s/token?v1" % url_base, http.send_request)

    time.sleep(1)
    urlRequest = http.send_request(url, set_request=set_request)

    grabInfo = json.loads(urlRequest.text)
    if 'error' in grabInfo.keys():
        raise Exception('error while trying to fetch info: %s' %
                        grabInfo['error'])
    if grabInfo['type'] == 'iframe':
        import urlresolver
        sLink = urlresolver.resolve(grabInfo['target'])
        return [('OpenLoad', sLink)]
    elif grabInfo['type'] == 'direct':
        return __9anime_extract_direct(url, grabInfo)

    raise Exception('Unknown case, please report')
````

Sooner or later there will be a solution for all

**Comment by DxCx** [comment]
@githubus11 we can provide urlresolver using our new repository at #44 
why not opening a PR?

**Comment by hoppler** [comment]
@DxCx please fork it (use the branch i made for you), as i wont maintain it. i was just doing the research but its for you to maintain it as i said in #44

**Comment by nerotix** [comment]
@hoppler does your fork also include where the playback failed error?

**Comment by hoppler** [comment]
@nerotix the zip in the repo.plugin... (master branch) includes the F1 sources fix (version 0.0.4) but remember that this wont be the official repo but is just the base for the fork @DxCx has to do. afterwards ill help with the repo but i dont want to be the maintainer of it.

all my forks of any kind of 9anime plugins are solely for making pullrequests and will be deleted afterwards. so dont assume they are accurate^^

**Comment by nerotix** [comment]
@hoppler Ah I see. So I can just download your fork as zip and install it for now, right? Did you also check the F3 errors? At the moment I get errors on F1 and F3 with "Playback failed".

**Comment by hoppler** [comment]
@nerotix im buildin the repo so it downloads urlresolver too. f3 was in the sourceslist for me but i didnt click on it. so maybe^^ currently the installation of urlresolver doesnt work so if you dont have it installed the 0.0.5 wont work which has all resent fixes. if you only wanna watch without openload take the 0.0.4

**Comment by nerotix** [comment]
@hoppler I think I had installation issues with urlresolver with a different plugin so I had to install it manually, I believe I got version 3.0.31 or something(?). So ill try version 0.0.5. Thanks for replying.

**Comment by hoppler** [comment]
my test was successful. it installed the dependency urlresolver on its own from my repository. so others can try too. @DxCx inform me when youre ready to fork the repo as i need to change the urls in the xml files before so it will work.

**Comment by DxCx** [comment]
cool thanks alot @hoppler , i meant like theortically it should be working, but you proved that already so that's awesome.
i planned to massing with the repo over the weekend so probably we are going to have new version & a repo next week :)

**Comment by hoppler** [comment]
@all based on reddit its a issue that will take a longer time to recover as bots are reporting the videos to google for deletion. therefore 9anime has to reupload every video that gets deleted again which seems quite a bit.

**Comment by Dranzera** [comment]
Yugioh dual monster doesn't work now but Yugioh Zero worked.

**Comment by DxCx** [comment]
@hoppler i have a future plans for something similar to what you suggested here,
we can take it offline if you want to hear more 👍

**Comment by DxCx** [comment]
Hey everyone,
i've just updated plugin for version 0.0.7 and now it support openload as well (Thanks @githubus11)
please give it a try and report back, 9anime itself has alot of issues lately but looks like openload works..

**Comment by DxCx** [comment]
any updates guys? is it better now?

**Comment by p1wookie** [comment]
It's been working fine here with the shows I watch on it.

**Comment by Dranzera** [comment]
Same here only thing that doesn't work and is no longer there is F2

________________________________

**Comment by p1wookie** [comment]
That may be due to 9anime itself. Sometimes f2 is the only option for me outside openload.

**Comment by DxCx** [comment]
well @Dranzera i've watched couple of F2 in the last 2 days,
wanted to tested it myself and it looks much better.
also, i noticed that some animes has also F4 server now.. actually had like 9 options yesterday night i was surprised.. :)

so, thanks for everybody who participated and helped making the sources more stable :)

**Comment by Dranzera** [comment]
Sorry man I actually meant F1, F2 is working great fot Yugioh and other anime too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DxCx** [comment]
hey @Dranzera can you please give me a link for episode which works on 9anime web but not on plugin?

**Comment by Dranzera** [comment]
The episodes I'm talking about work but there is no more F1 as a choice just F2

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DxCx** [comment]
@Dranzera but is F1 available through the site?
if the site removed F1, then we won't have it as well on plugin

**Comment by Dranzera** [comment]
I checked the website there's F2, F4 and Open Load for Yugioh dual monsters but no F1.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Dranzera** [comment]
F1 is not on the website.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DxCx** [comment]
yep that was exactly my point, plugin is working as expected =)

**Comment by Dranzera** [comment]
I never see F4 in Kodi though is there a reason for that?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DxCx** [comment]
Not using latest version maybe?
I can see alot of F4 sources here

**Comment by Dranzera** [comment]
Ah ok I'll get the new zip tonight then thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Dranzera** [comment]
Yugioh Dual Monsters episode 44 doesn't work in Kodi or the website.
Also Hayate no Gotoku doesn't work. There's only F4 and openload for these two in Kodi and neither work F4 says kog error and Openload has q message with a website in it.

**Comment by DxCx** [comment]
@Dranzera if you will visit the website on any other device in the same network, it will work as well.
unfortunately this is a requirement for openload

**Comment by DxCx** [comment]
@Dranzera i've seen this as well, but on 9anime website the same F4 that didn't work on kodi are not working as well (File deleted)

**Comment by Dranzera** [comment]
Oh no! these people continue to report and delete links that's so awful 😞

________________________________
